### ISSUE TITLE
TCP connection goes to sleep?

### ISSUE THREAD

**Issue by benswift** [negaex/extempore-atom#3]
If you're sending code a lot, it seems instant.  But if you don't send any code for a while, it slows right down and the eval latency spikes (on OSX). Is anyone else seeing this?

**Comment by noahingham** [comment]
Thanks Ben - I've also had this problem. I've found it hard to test a fix as the behaviour only appears occasionally on my machine. In the most recent commit I've added this line to the eval method, which, if it indeed does what the name suggests, might solve the problem. I'll wait and see if the problem persists.

```js
client.setKeepAlive(true,60000);
```

**Comment by zygurt** [comment]
I've also found this issue, and it still exists in 0.3.1.  I'm on El Capitan.  I've been meaning to check if it happens on my pc at home.
